/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Amount } from './amount';
import { Buyer } from './buyer';
import { DetailPayment } from './detailPayment';

export interface Aviso { 
    /**
     * Flujo asociado, es una constante
     */
    operacion?: string;
    /**
     * Fuente asociada, , es entregada al aliado y es diferente para ambiente de laboratorio y producción
     */
    cdFuente?: string;
    /**
     * Valor constante
     */
    usuario?: string;
    /**
     * Compañía de la Solución a recaudar; enviar 1000 para Seguros Generales o 2000 para Seguros de Vida
     */
    sociedad?: string;
    /**
     * Enviar vacío
     */
    formaPago?: string;
    /**
     * Conversión de Cuenta para la legalización. Dato suministrado por Sura, es distinto para cada fuente.
     */
    banco?: string;
    /**
     * Referencia externa asociada, consecutivo único de consumo del servicio debe ser generado por el aliado
     */
    refExterna?: string;
    amount?: Amount;
    buyer?: Buyer;
    /**
     * Cantidad, valor del monto a recaudar
     */
    detailPayment?: Array<DetailPayment>;
}