/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Amount } from './amount';

/**
 * Detalle del pago
 */
export interface DetailPayment { 
    /**
     * Compañía de la Solución a recaudar; enviar 1000 para Seguros Generales o 2000 para Seguros de Vida
     */
    sociedad?: string;
    /**
     * Consecutivo Único del Consumo del servicio, debe ser de 10 caracteres y es generado por quien consume el servicio
     */
    document?: string;
    /**
     * Año del documento, enviar año actual
     */
    year?: string;
    /**
     * Siempre enviar 001 si es una sola póliza la que se está recaudando
     */
    item?: string;
    /**
     * Número de Recibo (dato enviado en el servicio de sesión)
     */
    reference?: string;
    /**
     * Número de la Póliza o valor de la prepoliza (dato enviado en el servicio de sesión)
     */
    reference1?: string;
    /**
     * Fecha de pago en formato AAAA-MM-DD (dato enviado en el servicio de sesión)
     */
    baseDate?: string;
    amount?: Amount;
}