/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthRdSura } from './authRdSura';

/**
 * Cabecera para enviar en las peticiones
 */
export interface HeadRequestAviso { 
    /**
     * Compañía de la Solución a recaudar; enviar 1000 para Seguros Generales o 2000 para Seguros de Vida
     */
    sociedad?: string;
    /**
     * Fuente asociada, es entregada al aliado y es diferente para ambiente de laboratorio y producción
     */
    cdFuente: string;
    /**
     * Referencia externa asociada, es un consecutivo único que debe generar quien consume el servicio
     */
    refExterna?: string;
    authRdSura: AuthRdSura;
}