/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Buyer } from './buyer';
import { PaymentSession } from './paymentSession';

/**
 * Datos de autenticación el aliado
 */
export interface RedirectRequestSession { 
    buyer?: Buyer;
    payment?: PaymentSession;
    /**
     * Metodo de Pago, enviar vacío
     */
    paymentMethod?: string;
    /**
     * Fecha y hora del día actual en el cual se realizará el recaudo, se recomienda un periodo de 15 minutos, debe ser mayor a la fecha actual
     */
    expiration?: string;
    /**
     * Ip de donde se realiza el consumo
     */
    ipAddress?: string;
    /**
     * URL de retorno, se recomienda que sea el sitio del aliado
     */
    returnUrl?: string;
    /**
     * Valor constante
     */
    userAgent?: string;
}