/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DetailPayment } from './detailPayment';
import { HeadRequestCartera } from './headRequestCartera';

/**
 * Request para el registro de cartera
 */
export interface RequestRegistroCartera { 
    headRequest?: HeadRequestCartera;
    avsid?: string;
    cdFuente?: string;
    detailPayment?: Array<DetailPayment>;
}