/**
 * Plataforma Canales Masivos - API Plan Mascotas - Corresponsales
 * Servicios disponibles para el API de Plan Mascotas
 *
 * OpenAPI spec version: 1.0.1
 * Contact: ticanales@suramericana.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RespuestaExpedicion { 
    /**
     * Estado de la operación
     */
    estado: string;
    /**
     * Valor del seguro con impuestos.
     */
    primaTotal: string;
    /**
     * Identificador único de la póliza.
     */
    numeroNegocio: string;
    /**
     * Número de prepoliza.
     */
    prepoliza?: string;
    /**
     * Valor del impuesto del seguro.
     */
    impuestos: string;
    /**
     * Valor total del seguro sin impuestos.
     */
    primaNeta: string;
    /**
     * Resultado de la operación.
     */
    mensaje: string;
    /**
     * Inconsistencias encontradas.
     */
    errores: string;
}