/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusSession } from './statusSession';

export interface ResponseSession { 
    status?: StatusSession;
    /**
     * Id de Pasarela
     */
    requestId?: string;
    /**
     * Url de la sesión de pago, este es el link al cual se le debe redireccionar al cliente para realizar el pago
     */
    processUrl?: string;
    /**
     * Número de aviso o comprobante, este es un identificador único que permitirá consultar el estado del pago por medio del servicio de consulta
     */
    cdAviso?: string;
    /**
     * Referencia interna del proceso
     */
    internalReference?: string;
    authorization?: string;
    franchise?: string;
}