/**
 * API Recaudos y Desembolsos Sura - Colombia
 * Esta API ofrece operaciones para realizar recaudo, consulta de recaudo, creación de aviso (legalización) y registro de cartera. Sura - Colombia.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sopinfo@sura.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Cabecera para enviar en las peticiones
 */
export interface ResponseAvisoResponseAviso { 
    /**
     * Codigo de Respuesta
     */
    cdMensaje?: string;
    /**
     * Mensaje de respuesta
     */
    dsMensaje?: string;
    /**
     * Código Numero de Aviso
     */
    dsDato1?: string;
    /**
     * Fecha del día del consumo
     */
    dsDato2?: string;
    dsDato3?: string;
    dsDato4?: string;
}